// Generated by https://quicktype.io

export interface FlipbookTexture {
  flipbook_texture: string;
  atlas_tile: string;
  frames?: number[];
  ticks_per_frame?: number;
  replicate?: number;
  atlas_index?: number;
  atlas_tile_variant?: number;
  blend_frames?: boolean;
}
